version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: aipas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aipas
    ports:
      - '5432:5432'
    volumes:
      - aipas_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  aipas_pg_data:
